name: CI

on:
  push:
    branches: main

permissions:
  contents: read

env:
  # we need to have environment variables specified
  KAFKA_URI: ''
  POSTGRES_URI: ''

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Check with black
      run: |
        poetry run black --check .
    - name: Test with pytest
      run: |
        poetry run pytest